### PR TITLE
Added tab with server information on Help page

### PR DESCRIPTION
**Pull request by mslepko**
More server info on Help- >Info #23 

help-server_tab

### CODE REVIEW

**Comment by joelworsham** [comment]
Thanks @mslepko ! This all looks great. Could you please pass all readable text through proper localization though? So `__()` or `_e()`? Thanks!

**Comment by mslepko** [comment]
@joelworsham sure, what domain should I set in __($txt, $domain) or leave it empty ('default')?

**Comment by joelworsham** [comment]
Well, actually, looking into this more it seems that I was not even previously localizing properly throughout the plugin (most of this code is a couple years old). So, there is currently no text domain defined. I would say that, to be preemptive about it, use `client-dash`, so `__( $txt, 'client-dash' );`.

Thanks!

**Comment by mslepko** [comment]
@joelworsham updated

**Pull request closed without merging**
